### ISSUE TITLE
Server data

### ISSUE THREAD

**Issue by henry1778** [bigeyex/brackets-sftp-upload#47]
Hi, I don't find where server data were saved. 
I have searched on the plugin folder "bigeyex.brackets-sftp-upload" but I can't find json or xml with the data.

Thanks 
Henry

**Comment by bigeyex** [comment]
Hi, 

now server data are stored in the system level user preference file, as specified in this [line of code](https://github.com/bigeyex/brackets-sftp-upload/blob/master/main.js#L38) .

This extension was storing the server data as a json in the extension folder, but whenever there's an extension update, users will lose all their server data (as mentioned in #35 ). That's why we moved to the current solution.

it is still project folder independent, though.

**Comment by henry1778** [comment]
Thanks for the answer; I presume that is a good level of security for the data. Is correct?

**Comment by bigeyex** [comment]
The data is still unencrypted (for a mac, usually in ~/Library/Application Support/Brackets/brackets.json).

If your "security" means it won't be uploaded to the server / version control system, the answer is yes; but if somebody have access to your computer, s/he can still read your server credential. If this is a concern, use certificates instead.

**Comment by henry1778** [comment]
Thanks for the advice; and compliment for this usefull plugin. Have a great day.
Henry
